spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:cepdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
management:
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  metrics:
    export:
      prometheus:
        enabled: true