drop table if exists cep CASCADE ;
create table cep ( id bigint generated by default as identity, bairro varchar(255), cep varchar(255), cidade varchar(255), estado varchar(255), rua varchar(255), primary key (id));
create index IDX_CEP on cep (cep);
