drop table if exists cep CASCADE;
drop table if exists users CASCADE;
create table cep (id bigint generated by default as identity, bairro varchar(255), cep varchar(255), cidade varchar(255), estado varchar(255), rua varchar(255), primary key (id));
create table users (id bigint generated by default as identity, password varchar(255), username varchar(255), primary key (id));
create index IDX_CEP on cep (cep);
